### ISSUE TITLE
Selectively change a value

### ISSUE THREAD

**Issue by PanosPl** [cwmiller/broadworks-connector-net#11]
Congratulations of this extension.
Is there a chance you added a code example on how to selectively modify a value? 
I am trying to create a hotel interface that set the Guest Name on the extension when a guest checks in the room so the receptionist can see it once the guest contacts the reception.
I cannot find a single example in the internet on how to change specific "row" in a model based on criteria using OCI-P.
Thank you

**Comment by cwmiller** [comment]
Hello,

When it comes to modifying something, the OCIP API will only update the fields that are included in the request. This library follows that functionality. Any request you do to modify something will only modify the fields you set on the request object. Any non-specified field will retain its current value.

For example, with what you're trying to do, the following code will only update the First Name and Last Name fields on the user with user id `850@test.com`:

```csharp
var client = new OcipClient("...", "...", "...");

await client.CallAsync(new UserModifyRequest22
    {
        FirstName = "John",
        LastName = "Doe",
        UserId = "850@test.com"
    });
```

Hope this helps!
