### ISSUE TITLE
An error (The request was aborted: The request was canceled.) occurred while transmitting data over the HTTP channel.

### ISSUE THREAD

**Issue by ghost** [cwmiller/broadworks-connector-net#3]
Hi Chase,

It's me again. So I have overcome the previous errors that I raised after switching to a single client instance per thread. However after a couple days of running smooth I am noticing a bunch of the following errors coming through.

InnerException: An error (The request was aborted: The request was canceled.) occurred while transmitting data over the HTTP channel.

InnerException: The HTTP request to 'https://uccollab.t-systems.co.za/OCIOverSoap/services/ProvisioningService?wsdl' has exceeded the allotted timeout of 00:01:00. The time allotted to this operation may have been a portion of a longer timeout.

These seem to be very random and I am running the service on an EC2 instance in amazon with a very strong internet connection and so I assume the delay is coming from the Broadsoft side. 

Previously when I was using the JRE OCIClient I was able to pass a Command Timeout parameter but I have not been able to find anything similar in your connector. I have pulled the repo and taken a look through the code but I do not see anything about Command Timeouts. 

Are you able to give me some guidance if there is anything in place to increase this timeout.

Thanks,
Aaron

**Comment by cwmiller** [comment]
@AdaptIT-CPT I've just pushed out a new version, 1.2.0, which should resolve this for you. It adds some additional properties to `OcipClientOptions` (passed as the third argument to `OcipClient`'s constructor) to adjust timeout values. The one that applies to you in this scenario is the `SoapSendTimeout` which controls the timeout for sending + receiving when using SOAP. By default it's set to 60000 (1 minute).

Let me know if you have further issues with this.

**Comment by ghost** [comment]
@cwmiller Wow thank you again. Unbelievable really. I managed to resolve my issue last night using your suggestion from the previous ticket I raised about NO_OCI_CONNECTION by switching to using TCP it has completely eradicated the errors and seems to run a whole lot faster than the SOAP method. I appreciate the changes you made.

Thanks,
Aaron
