### ISSUE TITLE
Errored responses returning SuccessResponse in v2.1.0 vs throwing an ErrorResponseException in 1.4.1

### ISSUE THREAD

**Issue by andrewaggb** [cwmiller/broadworks-connector-net#8]
First I want to say thank you for publishing your library as it has saved me some time already.

I believe this is an unintentional regression.  I've found that CallAsync returns a SuccessResponse in v2.1.0 even when the soap message has an error.  In v1.4.1 an ErrorResponseException is thrown instead which I think is the intended behavior.  It seems easy to reproduce, I tried creating a GroupAccessDeviceAddRequest14 with Device type that doesn't exist in this case.  I've also tried creating a misconfigured GroupTrunkGroupAddInstanceRequest19sp1 with the same experience.  1.4.1 throws and exception, 2.1.0 silently fails by returning success.  I can help or look into myself if it's not something obvious.

eg
`<?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><processOCIMessageResponse xmlns="urn:com:broadsoft:webservice" xmlns:ns="urn:com:broadsoft:webservice"><processOCIMessageReturn>&lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
&lt;BroadsoftDocument protocol=&quot;OCI&quot; xmlns=&quot;C&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;sessionId xmlns=&quot;&quot;&gt;8728ab3815126d1961768b533495ae4d4523a9d7b834d04ce76cc34bd97bd393&lt;/sessionId&gt;&lt;command type=&quot;Error&quot; echo=&quot;&quot; xsi:type=&quot;c:ErrorResponse&quot; xmlns:c=&quot;C&quot; xmlns=&quot;&quot;&gt;&lt;summary&gt;[Error 4501] Device Type not found: Neo Trunk - 777&lt;/summary&gt;&lt;summaryEnglish&gt;[Error 4501] Device Type not found: Neo Trunk - 777&lt;/summaryEnglish&gt;&lt;/command&gt;&lt;/BroadsoftDocument&gt;</processOCIMessageReturn></processOCIMessageResponse></soapenv:Body></soapenv:Envelope>`

**Comment by cwmiller** [comment]
@andrewaggb Thanks for reporting this. I can't believe this slipped through the cracks.

I see the issue and should have it fixed soon.

**Comment by cwmiller** [comment]
This should now be fixed in version 2.1.1
